version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./backend/
    command: npm start --prefix /usr/src/app
    ports:
      - "38080:38080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/
    command: npm start --prefix /usr/src/app
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend